-- BundlesOfFun.Blind {
--     key = "damping",
--     name = "The Damping",
--     bundle = "enemies",
--     pos = { y = 5 },
--     atlas = "blind",
--     boss = { min = 4 },
--     boss_colour = HEX("8e7cca"),
--     calculate = function(self, blind, context)
--         if context.blind_disabled or context.blind_defeated then
--             for _, joker in ipairs(G.jokers.cards) do
--                 joker.ability.damping_chosen = nil
--             end
--         end

--         if blind.disabled then return end

--         if context.debuff_card and context.debuff_card.area == G.jokers then
--             if context.debuff_card.ability.damping_chosen then
--                 return { debuff = true }
--             end
--         end

--         if context.hand_drawn then
--             local is_final_hand = G.GAME.current_round.hands_left == 1
--             for _, joker in ipairs(G.jokers.cards) do
--                 local is_rare = joker.config.center_key and G.P_CENTERS[joker.config.center_key].rarity == 3
--                 local should_debuff = is_rare and not is_final_hand
--                 if joker.ability.damping_chosen ~= should_debuff then
--                     joker.ability.damping_chosen = should_debuff
--                     SMODS.recalc_debuff(joker)
--                     if should_debuff then joker:juice_up() end
--                 end
--             end
--             blind:wiggle()
--         end
--     end
-- }