-- BundlesOfFun.Blind {
--     key = "viscous",
--     name = "The Viscous",
--     bundle = "enemies",
--     pos = { y = 6 },
--     atlas = "blind",
--     boss = { min = 1 },
--     boss_colour = HEX("61b0af"),
--     calculate = function(self, blind, context)
--         if not blind.disabled then
--             local triggered = false
--             if context.individual and context.cardarea == G.play then
--                 context.other_card:juice_up()
--                 context.other_card.ability.perma_debuff = true
--                 triggered = true
--             end
--             if triggered then
--                 blind.triggered = true
--             end
--         end
--     end
-- }