[manifest]
version = "1.0.0"
dump_lua = true
priority = -2

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''local min_use = 100'''
position = "before"
payload = '''
local passport_eligible_blinds = eligible_bosses
'''
match_indent = true