[manifest]
version = "1.0.0"

# Pianoman joker: unlimited booster pack selection
# Modify booster pack size when opening booster packs
# Card:open()
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "local _size = *"
position = "after"
match_indent = true
payload = '''
if G.GAME.bof_pianoman_unlimited_boosters and not (G.GAME.jest_change_booster_options and (G.GAME.jest_change_booster_options.trigger or G.GAME.jest_change_booster_options.pack_choices == "unlimited")) then
    G.GAME.pack_choices = _size
end
'''
